export const ADD_TO_CONSTRUCTOR = 'ADD_TO_CONSTRUCTOR';
export const REMOVE_FROM_CONSTRUCTOR = 'REMOVE_FROM_CONSTRUCTOR';
export const DROP_CONSTRUCTOR_ITEM = 'DROP_CONSTRUCTOR_ITEM';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';
export const SHOW_DROP_LOCATION = 'SHOW_DROP_LOCATION';
export const HIDE_DROP_LOCATION = 'HIDE_DROP_LOCATION';

