export const ADD_TO_CONSTRUCTOR = 'ADD_TO_CONSTRUCTOR';
export const REMOVE_FROM_CONSTRUCTOR = 'REMOVE_FROM_CONSTRUCTOR';
export const DRAG_CONSTRUCTOR_ITEM = 'DRAG_CONSTRUCTOR_ITEM';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';
