export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT_PENDING = 'USER_LOGOUT_PENDING';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_UPDATE_PENDING = 'USER_UPDATE_PENDING';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REFRESH_TOKEN_PENDING = 'USER_REFRESH_TOKEN_PENDING';
export const USER_REFRESH_TOKEN_SUCCESS = 'USER_REFRESH_TOKEN_SUCCESS';
export const USER_REFRESH_TOKEN_FAIL = 'USER_REFRESH_TOKEN_FAIL';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const USER_RESET_PASSWOD_REQUEST_PENDING = 'USER_RESET_PASSWOD_REQUEST_PENDING';
export const USER_RESET_PASSWOD_REQUEST_SUCCESS = 'USER_RESET_PASSWOD_REQUEST_SUCCESS';
export const USER_RESET_PASSWOD_REQUEST_FAIL = 'USER_RESET_PASSWOD_REQUEST_FAIL';

export const USER_RESET_PASSWOD_PENDING = 'USER_RESET_PASSWOD_PENDING';
export const USER_RESET_PASSWOD_SUCCESS = 'USER_RESET_PASSWOD_SUCCESS';
export const USER_RESET_PASSWOD_FAIL = 'USER_RESET_PASSWOD_FAIL';
