export const INCREASE_TOTALCOST = 'INCREASE_TOTALCOST';
export const DECREASE_TOTALCOST = 'DECREASE_TOTALCOST';
export const RESET_TOTALCOST = 'RESET_TOTALCOST';
export const FETCH_DATA_ORDER_PENDING = 'FETCH_DATA_ORDER_PENDING';
export const FETCH_DATA_ORDER_SUCCESS = 'FETCH_DATA_ORDER_SUCCESS';
export const FETCH_DATA_ORDER_FAIL = 'FETCH_DATA_ORDER_FAIL';
export const SHOW_ORDER_DETAILS = 'SHOW_ORDER_DETAILS';
export const CLOSE_ORDER_DETAILS = 'CLOSE_ORDER_DETAILS';

